def write(sigmas,natoms,outdir,vsites, allatoms=False, q = 0.5, temp = 300, atoffset=0):
   if allatoms:
      satoms="ALLATOMS"
   else:
      lst=range(1+atoffset,natoms+atoffset+1)
      satoms = reduce(lambda i,j: str(i)+","+str(j), lst)
      satoms="ATOMS="+satoms
      
   if vsites:
      for i,s in enumerate(sigmas):
         fn=outdir+"plumed."+str(i)+".dat"
	 fh = open(fn,"w+")
	 sg="DSIGMA="+str(s)
	 plin="""
         ####### File generated by DIMERIZER #########
	 #######This is the replica index %d ######### 
         ##Basic configuration for a Gromacs Dimer 
         ##simulation with virtual sites.
         ##To be used with modified forcefields 
         ##containing the definition of the virtual sites
         ##Edit with what you need.
         #############################################
      
         dim: DIMER Q=%.2f TEMP=%.2f %s %s
      
         RESTRAINT ARG=dim AT=0 KAPPA=0 SLOPE=1 LABEL=dimforces
     
      
      
         PRINT ...
         ARG=dim
         STRIDE=10
         FILE=colvar.string
         ... PRINT 
      
         """ % (i,q,temp,sg,satoms)
      
         fh.write(plin)
         fh.close()
      
	 
   else:
      fh = open(outdir+"plumed.dat","w+")
      sgs = reduce(lambda i,j: str(i)+","+str(j) , sigmas)
      sgs="DSIGMA="+sgs
      plin="""
      ####### File generated by DIMERIZER #########
      ##Basic configuration for a Gromacs Dimer 
      ##simulation without virtual sites.
      ##To be used with standard forcefields 
      ##(no modifications required)
      ##Edit with what you need.
      #############################################
      
      dim: DIMER Q=%.2f TEMP=%.2f %s %s
      
      en: ENERGY
      
      RESTRAINT ARG=dim,en AT=0,0 KAPPA=0,0 SLOPE=1,-0.5 LABEL=dimforces
     
      
      
      PRINT ...
      ARG=dim,en
      STRIDE=10
      FILE=colvar.string
      ... PRINT 
      
      """ % (q,temp,sgs,satoms)
      
      fh.write(plin)
      fh.close()
